### ISSUE TITLE
Overall demographic diversity graph - data appears wrong

### ISSUE THREAD

**Issue by katleyq** [UCSB-MEDS/shiny-dashboard#20]
I'm pretty sure there are incoming students that are age 25+ in all cohorts. 
<img width="621" alt="Screenshot 2024-05-06 at 9 24 55 AM" src="https://github.com/UCSB-MEDS/shiny-dashboard/assets/53875361/49610e3c-9a51-4298-a217-da6485eec7bf">

**Comment by samanthacsik** [comment]
Thanks for noting this @katleyq !! Not sure what was going on there, but things seem to make more sense in this current update (digging into the data too shows what seem to be the correct number of 25+ year olds in each of the past 3 years of MEDS)...

![Screenshot 2024-07-01 at 10 26 57 AM](https://github.com/UCSB-MEDS/shiny-dashboard/assets/43836046/b40531f5-4307-4099-9855-e39084e4530a)
